sequenceDiagram 
    participant browser
    participant server
    
    browser->>server: POST https://studies.cs.helsinki.fi/exampleapp/new_note
    activate server
    server->>browser: Request was redirected
    deactivate server

    Note right of browser: Request was redirected to notes.

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/notes
    activate server
    server->>browser: HTML Document
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.css
    activate server
    server->>browser: CSS File
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.js
    activate server
    server->>browser: Javascript File
    deactivate server
    
    Note right of browser: When the browser starts executing the javascript code, it will execute the code that fetches the json data.
    
    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/data.json
    activate server
    server->>browser: [{"content": "Creating+sequence+digram", "date":"2023-12-21"}]
    deactivate server

    Note right of browser : The broswer executes a callback function that renders the array of notes